In [3]:
import numpy as np

a = np.array([1,2,3,4,5])
b = a.copy()
a[1] = 40
print(a)
print(b)

[ 1 40  3  4  5]
[1 2 3 4 5]


In [ ]:
a = np.array([1,2,3,4,5])
b = a.view() #change in a changes b and changes in b causes change in a
print(a)
print(b)

a[1] = 30

print(a)
print(b)

In [6]:
a = np.array([[1,2,3,4,5],[6,7,8,9,0]])
b = a.copy().transpose()
a[0][0] = 40
print(a)
print()
print(b)

[[40  2  3  4  5]
 [ 6  7  8  9  0]]

[[1 6]
 [2 7]
 [3 8]
 [4 9]
 [5 0]]
