In [1]:
import numpy as np

arr1 = np.zeros(4) # A single row with 4 columns filled with zeros completely
print(arr1)

print()

arr2 = np.zeros((3,4)) #three rows with 4 columns each filled with zeros completely
print(arr2)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [2]:
arr3 = np.ones(4)  # A single row with 4 columns filled with ones completely
print(arr3)

print()

arr4 = np.ones((3,4))   #three rows with 4 columns each filled with ones completely
print(arr4)

print()

arr5 = np.empty(4)      # A single row with 4 columns filled with ones completely
print(arr5)

print()

arr6 = np.empty((3,4))      #three rows with 4 columns each filled with ones completely
print(arr6) 

[1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [3]:
arr7 = np.arange(4)   #counting from zero excludes the number given
print(arr7)

[0 1 2 3]


In [4]:
arr8 = np.eye(4)  #prints n numbers of 1s in diagonal representation with n by n rows and columns
print(arr8)
print(arr8.ndim)  

print()

arr9 = np.eye(3,5)      #prints n numbers of 1s in diagonal representation with custom rows and columns
print(arr9)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
2

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [5]:
arr10 = np.linspace(1,10,num=5)  #prints num numbers between the range with a fixed diff between every number
print(arr10)

[ 1.    3.25  5.5   7.75 10.  ]
