In [ ]:
import numpy as np

arr1 = np.random.rand(4)  #n random numbers between 0 and 1 of 1 dimension where n = no of columns
print(arr1)

print()

arr2 = np.random.rand(2,5)  #n random numbers between 0 and 1 of 2 dimension where n =  no of columns
print(arr2) #

print()

arr3 = np.random.rand(2,3,4)  #n random numbers between 0 and 1 of 3 dimension where n =  no of columns
print(arr3)

In [ ]:
arr4 = np.random.randn(4) #n random numbers close to zero ( +ve or -ve) of 1 dimensions where n= no fo columns
print(arr4)

print()

arr5 = np.random.randn(2,5)  #n random numbers close to zero ( +ve or -ve) of 2 dimensions where n= no fo columns
print(arr5)

print()

arr6 = np.random.randn(2,3,4) #n random numbers close to zero ( +ve or -ve) of 3 dimensions where n= no fo columns
print(arr6)

In [ ]:
arr7 = np.random.ranf(4)   #n random numbers . returns an array of specified shape and fills it with random float in half open interval
print(arr7)


In [ ]:
arr8 = np.random.randint(0,9,12) # syntax : arr8 = np.random.randint(mix,max,total_no_of_values). repetitions allowed
print(arr8)

In [ ]:
arr1 = np.random.random((2,5)) #range is 0 to 1 in float, 2 stands for rows and 5 stands for columns
print(arr1)
print()

arr2 = np.random.default_rng() #random values between 0 and 1 in float 
b = arr2.random((3,4)) # 3 stands for rows and 4 stands for columns
print(b) 

In [15]:
a = np.random.randint(10,size=(3,4))
print(a)
print()
b = np.random.default_rng()
c = b.integers(42, size=(3,4))
print(c)

[[1 9 2 2]
 [2 8 8 0]
 [4 2 2 4]]

[[12 29 41  1]
 [16 18  5  2]
 [28 33 29 29]]
