In [ ]:
import numpy as np

a1 = np.array([1,2,3,4])

print(a1[2])  #indexing
print(a1[-3])

In [ ]:
a1 = np.array([[1,2,3,4],[5,6,7,8]])

print(a1[0][-2])
print(a1[1,-3])

In [12]:
a1 = np.array([[[1,2],[3,4],[5,6]]])
print(a1[0,1,1])
print(a1[0,2,0])

4
5


In [ ]:
a1 = np.array([1,2,3,4])
print(a1[:2])
print(a1[1:4])

In [11]:
a1 = np.array([[1,2,3,4],[5,6,7,8]])
print(a1[1,1:4])
print(a1[0,:3])

[6 7 8]
[1 2 3]


In [16]:
a1 = np.array([[[1,2,3,4],[3,4,5,6],[10,12,12,24]]])
print(a1[0,1,1:5])
print(a1[0,2,1:5])
print(a1[0,0,:4])

[4 5 6]
[12 12 24]
[1 2 3 4]
