In [ ]:
import numpy as np

a = np.matrix([[1,2,3],[4,5,6]])
print(a)
print()
print(np.transpose(a)) #transpose of a matrix
print()
print(a.T) #transpose of a matrix
print()
b = a.transpose()
a[0][0] = 42
print(b)
print()
print(a)

In [12]:
a = np.array([[1,2,3],[4,5,6]]) #transpose of array
b = a.transpose()
a[0][0] = 42
print(b)
print()
print(a)

[[42  4]
 [ 2  5]
 [ 3  6]]

[[42  2  3]
 [ 4  5  6]]


In [ ]:
a = np.matrix([[1,2,3],[4,5,6]])
print(np.swapaxes(a,0,1)) #changes rows of a matrix to columns and vice versa


In [ ]:
a = np.matrix([[1,2],[3,4]])
print(a)
print()

print(np.linalg.inv(a)) #inverse of a matrix

In [ ]:
a = np.matrix([[1,2],[3,4]])
print(a)
print()
print(np.linalg.matrix_power(a,2)) #power of the matrix where 2 means square if it was 3 then cube
print()
print(np.linalg.matrix_power(a,0)) #returns identity matrix
print()
print(np.linalg.matrix_power(a,-2)) #inverse to the power of the matrix

In [ ]:
a = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
b = np.matrix([[1,2],[4,5]])
print(a)
print()
print(b)
print()
print(np.linalg.det(a))
print(np.linalg.det(b))
