In [10]:
import numpy as np

a = np.array([1,2,2,3,4,5,5,8,9])
b = np.where( a==2 ) #where is used for conditional statements like a==2 returns all the indices where 2 appears
print(b)
print()
c = np.where((a%2) == 0) #returns indices of numbers which satisfy the condition a%2==0
print(c)

(array([1, 2]),)

(array([1, 2, 4, 7]),)


In [17]:
d = np.searchsorted(a,[5,6]) #sorts the array and returns the index where a certain number will be entered
print(d)
e = np.searchsorted(a,[0,4],side="right") #sorts the array and returns the index where a certain number will be entered
print(e)

[5 7]
[0 5]


In [ ]:
a = np.array([[[9,4,6],[7,3,9],[1,8,5]]])
f = np.sort(a) #array sorting
print(f)
print()
g = np.array(['a','z','g','d','v'])
h = np.sort(g)
print(h)

In [ ]:
g = np.array(['a','z','g','d','v'])
i = [True,False,False,True,True]

z =g[i] #array filtering
print(z)

In [ ]:
a = np.array([1,2,3,4,5])
np.random.shuffle(a) #shuffles the array and returns
print(a)

In [ ]:
a = np.array([1,2,3,4,3,2,1,4,1,3,4,3,2,1,3,1])
b = np.unique(a, return_index=True , return_counts=True) #removes duplicates and print them , their indexes and no of duplicates in total
print(b)


In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9])
b = np.resize(a,(3,3)) #resizes the array from nth dimension to n+1th dimension
print(b)
print()
c = b.flatten()
print(c)
d = b.flatten(order="F")
print(d)

In [ ]:
a = np.array([1,2,3,4])
print(a)
print()
b = np.insert(a, 2, 40) #insert item at a specific index in the array
print(b)
print()
c = np.insert(a, (2,4), 38) #add item to multiple indexes in array
print(c)
print()
d = np.insert(a, (2,4), 6.54) #adds the integer and ignore the part after decimal
print(d)
print()
x = np.append(a,6.545)
print(x)

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
b = np.insert(a, 2,7, axis=0)
print(b)
print()
c = np.insert(a, 2, 7, axis=1)
print(c)
print()
d = np.insert(a, 1, [22,54], axis=1)
print(d)
print()

In [ ]:
a = np.array([[1,2,3],[5,6,7]])
print(a)
print()
x = np.append(a, [[34,65,17]], axis=0)
print(x)


In [42]:
a = np.array([1,2,3,4])
print(a)
print()
x = np.delete(a, 3) #delete the item present on the specified index
print(x)


[1 2 3 4]

[1 2 3]
