In [ ]:
import numpy as np

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(b,a))
print(np.mod(b,a))
print(np.power(a,b))
print(np.reciprocal(a))

In [6]:
a = np.array([[1,2,3,4],[6,7,8,9]])
b = np.array([[5,6,7,8],[1,2,3,4]])

print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(b,a))
print(np.mod(b,a))
print(np.power(a,b))
print(np.reciprocal(a))
print(np.reciprocal(b))


[[ 6  8 10 12]
 [ 7  9 11 13]]
[[-4 -4 -4 -4]
 [ 5  5  5  5]]
[[ 5 12 21 32]
 [ 6 14 24 36]]
[[5.         3.         2.33333333 2.        ]
 [0.16666667 0.28571429 0.375      0.44444444]]
[[0 0 1 0]
 [1 2 3 4]]
[[    1    64  2187 65536]
 [    6    49   512  6561]]
[[1 0 0 0]
 [0 0 0 0]]
[[0 0 0 0]
 [1 0 0 0]]
