In [6]:
import numpy as np

a = np.array([1,2,3,4,5])
b = np.array([3,4,5,6,7])
c = np.array([[1,2,-3,-4],[-5,-76,12,-45]])
d = np.array([True,True,False])


print(np.min(a))
print(np.max(a))
print(np.argmin(a))     #returns index of the minimum element of the array
print(np.argmax(a))     #returns index of the minimum element of the array
print(np.sqrt(a))
print(np.sin(a))
print(np.cos(a))
print(np.cumsum(a)) #cumulative sum of elements
print(np.matmul(a,b))
print(np.absolute(c))
print(d.dtype)
print(d)
print()
z = np.logical_not(d)
print(z.dtype)
print(z)
print()

1
5
0
4
[1.         1.41421356 1.73205081 2.         2.23606798]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
[ 1  3  6 10 15]
85
[[ 1  2  3  4]
 [ 5 76 12 45]]
bool
[ True  True False]

bool
[False False  True]



ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()