In [ ]:
import numpy as np

a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print()
print(a.shape)

In [ ]:
a = np.array([1,2,3,4], ndmin = 4)
print(a)
print()
print(a.ndim)
print()
print(a.shape)

In [15]:
a = np.array([1,2,3,4,5,6])
x = a.reshape(3,2) #3 = rows and 2 = columns
print(x)
print(x.ndim)
print()
b = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
y = b.reshape(2,3,2)
print(y)
print(y.ndim)
print()
c = b.reshape(-1)
print(c)


[[1 2]
 [3 4]
 [5 6]]
2

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3

[ 1  2  3  4  5  6  7  8  9 10 11 12]
